fix: fix json reading

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,6 +27,9 @@ jobs:
           echo "subdomains_matrix=$SUBDOMAIN_MATRIX" >> $GITHUB_ENV
           echo "::set-output name=subdomains_matrix::$SUBDOMAIN_MATRIX"
 
+      - name: 1.3. Debug Output
+        run: echo "Subdomains Matrix $SUBDOMAIN_MATRIX"
+
   deploy:
     name: 2. Deploy to Subdomains
     needs: fetch-subdomains
@@ -36,10 +39,6 @@ jobs:
       matrix:
         node-version: [20.12.1]
         subdomain: ${{ fromJson(needs.fetch-subdomains.outputs.subdomains) }}
-
-    concurrency:
-      group: deploy-subdomains-${{ matrix.subdomain.sub }}
-      cancel-in-progress: false
 
     steps:
       - name: 2.1. Get latest code
@@ -107,10 +106,6 @@ jobs:
     needs: deploy
     runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        subdomain: ${{ fromJson(needs.fetch-subdomains.outputs.subdomains) }}
-
     steps:
       - name: 3.1. Checkout code
         uses: actions/checkout@v2
@@ -122,13 +117,15 @@ jobs:
 
       - name: 3.3. Commit and Push Updated Sitemap Files
         run: |
-          sitemap_file="public/${{ matrix.subdomain.sub }}_sitemap.xml"
-          if [ -f "$sitemap_file" ]; then
-            git add "$sitemap_file"
-            git commit -m "Update ${{ matrix.subdomain.sub }}_sitemap.xml from GitHub Actions" || echo "No changes to commit"
-            git fetch origin area
-            git pull origin area --rebase || echo "Rebase failed, not pulling"
-            git push origin area || echo "Push failed"
-          else
-            echo "No sitemap file found for ${{ matrix.subdomain.sub }}."
-          fi
+          for subdomain in ${{ fromJson(needs.fetch-subdomains.outputs.subdomains) }}; do
+            sitemap_file="public/${{ subdomain.sub }}_sitemap.xml"
+            if [ -f "$sitemap_file" ]; then
+              git add "$sitemap_file"
+              git commit -m "Update ${{ subdomain.sub }}_sitemap.xml from GitHub Actions" || echo "No changes to commit"
+              git fetch origin area
+              git pull origin area --rebase || echo "Rebase failed, not pulling"
+              git push origin area || echo "Push failed"
+            else
+              echo "No sitemap file found for ${{ subdomain.sub }}."
+            fi
+          done
